</$objtype/mkfile

TARG=lumen
OFILES=main.$O\
		model.$O\
		sampler.$O\
		tensor.$O\
		transformer.$O\
		loader-simple.$O\
		loader-gguf.$O\

HFILES=common.h\
		model.h\
	   
BIN=$home/bin/$objtype

</sys/src/cmd/mkone
